// ============================================================
// cadcvt/reader/SwReader.cpp
//
// SolidWorks COM-automation reader. All SolidWorks SDK / COM types
// are confined to this translation unit (the header is COM-free, per
// the Reader.h contract). The #import directives live in the
// CMake-generated SwImports.h, which carries the machine-specific
// absolute paths to sldworks.tlb / swconst.tlb / swpublished.tlb.
//
// The whole reader is gated by CAX_SW_OK: when SolidWorks is not
// installed (no type libs found at configure time) this file is not
// compiled at all and SwReader is unavailable.
// ============================================================

#include "cadcvt_c/reader/SwReader.h"

#ifdef CAX_SW_OK

#include "cadapp_c/ir/SketchIR.h"
#include "cadapp_c/ir/Enums.h"

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <comdef.h>
#include <oleauto.h>

// Generated by CMake; emits:
//   #import "<dir>/swconst.tlb"    no_namespace, named_guids
//   #import "<dir>/swpublished.tlb" no_namespace, named_guids
//   #import "<dir>/sldworks.tlb"   no_namespace, named_guids
#include "SwImports.h"

#include <cmath>
#include <cstdio>
#include <cstring>
#include <stdexcept>
#include <string>
#include <thread>
#include <utility>
#include <vector>

namespace cadcvt
{
namespace
{

// ---- small COM helpers -------------------------------------------------

// BSTR / _bstr_t -> UTF-8 std::string. SolidWorks names are localized
// (UTF-16); we keep them as UTF-8 in the IR so they round-trip cleanly.
std::string Utf8(const BSTR b)
{
    if (!b) {
        return {};
    }
    int len = ::SysStringLen(b);
    if (len <= 0) {
        return {};
    }
    int n = ::WideCharToMultiByte(CP_UTF8, 0, b, len, nullptr, 0, nullptr, nullptr);
    std::string out((size_t)n, '\0');
    ::WideCharToMultiByte(CP_UTF8, 0, b, len, out.data(), n, nullptr, nullptr);
    return out;
}

std::string Utf8(const _bstr_t& b)
{
    const wchar_t* w = b;        // operator const wchar_t*; buffer is a real BSTR
    if (!w) {
        return {};
    }
    return Utf8((BSTR)w);
}

std::wstring Widen(const std::string& s)
{
    if (s.empty()) {
        return {};
    }
    int n = ::MultiByteToWideChar(CP_UTF8, 0, s.data(), (int)s.size(), nullptr, 0);
    std::wstring out((size_t)n, L'\0');
    ::MultiByteToWideChar(CP_UTF8, 0, s.data(), (int)s.size(), out.data(), n);
    return out;
}

bool EndsWithICase(const std::string& s, const char* suf)
{
    size_t sl = s.size(), xl = std::strlen(suf);
    if (xl > sl) return false;
    for (size_t i = 0; i < xl; ++i) {
        if (std::tolower((unsigned char)s[sl - xl + i]) !=
            std::tolower((unsigned char)suf[i])) {
            return false;
        }
    }
    return true;
}

// Map SolidWorks swEndConditions_e -> cadapp::ExtrudeEndType.
cadapp::ExtrudeEndType MapEndCond(long sw)
{
    using E = cadapp::ExtrudeEndType;
    switch (sw) {
        case 0:  return E::Blind;           // swEndCondBlind
        case 1:  return E::ThroughAll;      // swEndCondThroughAll
        case 2:  return E::UpToFirst;       // swEndCondThroughNext
        case 3:  return E::UpToVertex;      // swEndCondUpToVertex
        case 4:  return E::UpToSurface;     // swEndCondUpToSurface
        case 5:  return E::OffsetFromSurface;
        case 6:  return E::MidPlane;        // swEndCondMidPlane
        default: return E::Blind;
    }
}

// Read a sketch's world plane from ISketch::IModelToSketchTransform.
// The inverse (sketch->model) ArrayData is 16 doubles:
//   [0..8]  3x3 rotation (row-major)
//   [9..11] translation (origin in model space)
//   [12]    scale
// The sketch local X axis maps to model column 0 = (d0,d3,d6); the
// normal maps to model column 2 = (d2,d5,d8).
void ReadSketchPlane(ISketchPtr sk, double scale, cadapp::SketchIR& out)
{
    // sensible default (world XY) if anything below fails
    out.plane_origin[0] = out.plane_origin[1] = out.plane_origin[2] = 0.0;
    out.plane_x_dir[0]  = 1.0; out.plane_x_dir[1]  = 0.0; out.plane_x_dir[2]  = 0.0;
    out.plane_normal[0] = 0.0; out.plane_normal[1] = 0.0; out.plane_normal[2] = 1.0;

    IMathTransformPtr m2s = sk->GetModelToSketchTransform();
    if (!m2s) {
        return;
    }
    IMathTransformPtr s2m = m2s->IInverse();
    if (!s2m) {
        return;
    }
    _variant_t arr = s2m->GetArrayData();
    if (arr.vt != (VT_ARRAY | VT_R8)) {
        return;
    }
    SAFEARRAY* sa = arr.parray;
    double* d = nullptr;
    if (FAILED(::SafeArrayAccessData(sa, (void**)&d))) {
        return;
    }
    long lb = 0, ub = 0;
    ::SafeArrayGetLBound(sa, 1, &lb);
    ::SafeArrayGetUBound(sa, 1, &ub);
    if (ub - lb + 1 >= 13) {
        out.plane_x_dir[0]  = d[0]; out.plane_x_dir[1]  = d[3]; out.plane_x_dir[2]  = d[6];
        out.plane_normal[0] = d[2]; out.plane_normal[1] = d[5]; out.plane_normal[2] = d[8];
        out.plane_origin[0] = d[9]  * scale;
        out.plane_origin[1] = d[10] * scale;
        out.plane_origin[2] = d[11] * scale;
    }
    ::SafeArrayUnaccessData(sa);
}

// Append one sketch segment to the SketchIR as an SkGeoIR. Coordinates
// come back from SolidWorks in sketch-local metres.
void AppendSegment(ISketchSegmentPtr seg, uint32_t id, double scale,
                   cadapp::SketchIR& sk)
{
    long t = seg->GetType();   // swSketchSegments_e: 0 line 1 arc 2 ellipse 3 spline
    bool construction = (seg->ConstructionGeometry == VARIANT_TRUE);

    if (t == 0) // line
    {
        ISketchLinePtr ln(seg);
        if (!ln) return;
        ISketchPointPtr a = ln->IGetStartPoint2();
        ISketchPointPtr b = ln->IGetEndPoint2();
        if (!a || !b) return;
        sk.geos.push_back(cadapp::SkGeoIR::Line(
            id, a->GetX() * scale, a->GetY() * scale,
            b->GetX() * scale, b->GetY() * scale,
            construction));
    }
    else if (t == 1) // arc or full circle
    {
        ISketchArcPtr ar(seg);
        if (!ar) return;
        ISketchPointPtr c = ar->IGetCenterPoint2();
        ISketchPointPtr a = ar->IGetStartPoint2();
        ISketchPointPtr b = ar->IGetEndPoint2();
        if (!c) return;
        double cx = c->GetX() * scale, cy = c->GetY() * scale;
        double r  = ar->GetRadius() * scale;
        // Full circle when start ~ end (SolidWorks models circles as a
        // closed arc). Otherwise emit an arc with angles from the
        // endpoints.
        bool full = true;
        double sa = 0.0, ea = 0.0;
        if (a && b) {
            double ax = a->GetX() * scale, ay = a->GetY() * scale;
            double bx = b->GetX() * scale, by = b->GetY() * scale;
            double dd = (ax - bx) * (ax - bx) + (ay - by) * (ay - by);
            full = dd < 1e-14;
            sa = std::atan2(ay - cy, ax - cx);
            ea = std::atan2(by - cy, bx - cx);
        }
        if (full) {
            sk.geos.push_back(cadapp::SkGeoIR::Circle(id, cx, cy, r, construction));
        } else {
            sk.geos.push_back(cadapp::SkGeoIR::Arc(id, cx, cy, r, sa, ea, construction));
        }
    }
    // ellipse / spline: not in the v1 vertical slice
}

// ---- sketch constraints (relations + dimensions) ----------------------
//
// SolidWorks exposes a sketch's constraints via ISketchRelationManager
// (GetRelations) as ISketchRelation objects, each carrying a typed kind
// (swConstraintType_e) + the sketch entities it binds. Dimensions
// (distance / angle / radius / diameter) ride along as relations too,
// with the magnitude reachable through GetDisplayDimension. We correlate
// each relation entity (raw segment / endpoint object) back to the
// SkGeoIR id + SkPointPos already emitted, using tables built while the
// segments were read: segment identity (ISketchSegment::GetID) for whole
// geometries, and endpoint coordinates for points.

struct PtRef {
    long               pid;       // ISketchPoint::IGetID() -- endpoint identity
    double             x, y;      // sketch-local coords (scaled) -- for corner synthesis
    uint32_t           geo_id;
    cadapp::SkPointPos pos;
};

// Record a segment's identity + endpoint identity + endpoint coordinates
// for entity correlation. Mirrors AppendSegment's type handling; only the
// kinds AppendSegment actually emits (line / arc / circle) are recorded, so
// a recorded id always points at a real SkGeoIR.
void RecordSegmentRefs(ISketchSegmentPtr seg, uint32_t geo_id, double scale,
                       std::vector<std::pair<long, uint32_t>>& seg2geo,
                       std::vector<PtRef>&                      pts)
{
    auto add = [&](ISketchPointPtr p, cadapp::SkPointPos pos) {
        if (p) pts.push_back({ p->IGetID(), p->GetX() * scale, p->GetY() * scale, geo_id, pos });
    };
    long t = seg->GetType();
    if (t == 0) {                       // line
        ISketchLinePtr ln(seg);
        if (!ln) return;
        seg2geo.push_back({ seg->IGetID(), geo_id });
        add(ln->IGetStartPoint2(), cadapp::SkPointPos::Start);
        add(ln->IGetEndPoint2(),   cadapp::SkPointPos::End);
    } else if (t == 1) {                 // arc / circle
        ISketchArcPtr ar(seg);
        if (!ar) return;
        seg2geo.push_back({ seg->IGetID(), geo_id });
        add(ar->IGetCenterPoint2(), cadapp::SkPointPos::Center);
        add(ar->IGetStartPoint2(),  cadapp::SkPointPos::Start);
        add(ar->IGetEndPoint2(),    cadapp::SkPointPos::End);
    }
}

// swConstraintType_e -> cadapp::SkConsType. value_bearing is set for the
// dimensional kinds, whose magnitude is read from the display dimension.
// Returns None for kinds we do not map (skipped). RADIUS / DIAMETER map to
// the Circle* variant here and are switched to Arc* by the caller once the
// referenced geometry's type is known.
cadapp::SkConsType MapConsType(long sw, bool& value_bearing)
{
    using C = cadapp::SkConsType;
    value_bearing = false;
    switch (sw) {
        case 4:  return C::Horizontal;     // swConstraintType_HORIZONTAL
        case 5:  return C::Vertical;       // VERTICAL
        case 6:  return C::Tangent;        // TANGENT
        case 7:  return C::Parallel;       // PARALLEL
        case 8:  return C::Perpendicular;  // PERPENDICULAR
        case 9:  return C::None;           // COINCIDENT -- synthesized from shared endpoint coords instead
        case 10: return C::Concentric;     // CONCENTRIC
        case 11: return C::Symmetric;      // SYMMETRIC
        case 14: return C::Equal;          // SAMELENGTH
        case 17: return C::Fix;            // FIXED
        case 27: return C::Colinear;       // COLINEAR
        case 1:  value_bearing = true; return C::Distance;       // DISTANCE
        case 2:  value_bearing = true; return C::Angle;          // ANGLE
        case 3:  value_bearing = true; return C::CircleRadius;   // RADIUS
        case 15: value_bearing = true; return C::CircleDiameter; // DIAMETER
        default: return C::None;
    }
}

// Non-throwing QueryInterface. _com_ptr_t's raw-pointer constructor and
// assignment THROW _com_error on QI failure, so building e.g.
// ISketchSegmentPtr from a relation entity that is actually a point would
// abort the whole load (SolidWorks even returns DISP_E_TYPEMISMATCH rather
// than E_NOINTERFACE for the miss). This yields a null smart ptr instead --
// the behaviour the `if (ptr)` checks below assume.
template <class Ptr>
Ptr TryQI(IDispatch* p)
{
    Ptr out;
    if (p) {
        p->QueryInterface(__uuidof(typename Ptr::Interface),
                          reinterpret_cast<void**>(&out));
    }
    return out;
}

// Resolve a relation entity (whole segment or an endpoint) to a SkGeoRef
// against the correlation tables. Unresolved -> default ref (geo_id
// 0xFFFFFFFF), which the rebuild path drops.
cadapp::SkGeoRef ResolveEntity(IDispatchPtr ent,
                               const std::vector<std::pair<long, uint32_t>>& seg2geo,
                               const std::vector<PtRef>&                     pts)
{
    cadapp::SkGeoRef ref;
    if (!ent) return ref;

    ISketchSegmentPtr seg = TryQI<ISketchSegmentPtr>(ent);
    if (seg) {
        long id = seg->IGetID();
        for (const auto& kv : seg2geo) {
            if (kv.first == id) {
                ref.geo_id    = kv.second;
                ref.point_pos = cadapp::SkPointPos::None;
                return ref;
            }
        }
        return ref;
    }
    ISketchPointPtr pt = TryQI<ISketchPointPtr>(ent);
    if (pt) {
        long pid = pt->IGetID();
        for (const auto& p : pts) {
            if (p.pid == pid) {
                ref.geo_id    = p.geo_id;
                ref.point_pos = p.pos;
                return ref;
            }
        }
    }
    return ref;
}

// Read every sketch relation + dimension and append the mappable ones to
// out.cons.
void ReadSketchConstraints(ISketchPtr sk, double scale,
                           const std::vector<std::pair<long, uint32_t>>& seg2geo,
                           const std::vector<PtRef>&                     pts,
                           uint32_t&                                     next_cons_id,
                           cadapp::SketchIR&                             out)
{
    // Synthesize Coincident constraints from endpoints that share a
    // location. SolidWorks joins connected geometry (corner rectangles,
    // polylines) by MERGING endpoints into one shared sketch point rather
    // than authoring explicit coincident relations -- a corner-rectangle's
    // only relations are the 2 horizontal + 2 vertical, and the 4 corners
    // carry none. Without rejoining them the rebuilt sketch is 4 loose
    // lines and the solver collapses it. Pairing endpoints at equal coords
    // (different geometries) reconstructs the joins; in a solved/imported
    // model coincident endpoints are exactly equal, so this is unambiguous.
    const double kTol2 = 1e-16;   // (1e-8 m)^2
    auto endpoint = [](cadapp::SkPointPos p) {
        return p == cadapp::SkPointPos::Start || p == cadapp::SkPointPos::End;
    };
    for (size_t i = 0; i < pts.size(); ++i) {
        if (!endpoint(pts[i].pos)) continue;            // corners only, not arc centers
        for (size_t j = i + 1; j < pts.size(); ++j) {
            if (!endpoint(pts[j].pos)) continue;
            if (pts[i].geo_id == pts[j].geo_id) continue;
            double dx = pts[i].x - pts[j].x;
            double dy = pts[i].y - pts[j].y;
            if (dx * dx + dy * dy > kTol2) continue;
            cadapp::SkConsIR c;
            c.id          = next_cons_id++;
            c.type        = cadapp::SkConsType::Coincident;
            c.a.geo_id    = pts[i].geo_id; c.a.point_pos = pts[i].pos;
            c.b.geo_id    = pts[j].geo_id; c.b.point_pos = pts[j].pos;
            c.value       = 0.0;
            c.driving     = true;
            out.cons.push_back(c);
        }
    }

    ISketchRelationManagerPtr rm = sk->GetRelationManager();
    if (!rm) return;
    _variant_t v = rm->GetRelations(0 /*swAll*/);
    if (v.vt != (VT_ARRAY | VT_DISPATCH)) return;
    SAFEARRAY* sa = v.parray;
    long lb = 0, ub = -1;
    ::SafeArrayGetLBound(sa, 1, &lb);
    ::SafeArrayGetUBound(sa, 1, &ub);
    IDispatch** items = nullptr;
    if (FAILED(::SafeArrayAccessData(sa, (void**)&items))) return;

    for (long i = lb; i <= ub; ++i) {
        ISketchRelationPtr rel(items[i - lb]);
        if (!rel) continue;

        bool value_bearing = false;
        cadapp::SkConsType ct = MapConsType(rel->GetRelationType(), value_bearing);
        if (ct == cadapp::SkConsType::None) continue;

        // Up to two entities -> refs.
        cadapp::SkGeoRef a, b;
        _variant_t ev = rel->GetEntities();
        if (ev.vt == (VT_ARRAY | VT_DISPATCH)) {
            SAFEARRAY* esa = ev.parray;
            long elb = 0, eub = -1;
            ::SafeArrayGetLBound(esa, 1, &elb);
            ::SafeArrayGetUBound(esa, 1, &eub);
            IDispatch** ei = nullptr;
            if (SUCCEEDED(::SafeArrayAccessData(esa, (void**)&ei))) {
                long n = eub - elb + 1;
                if (n >= 1) a = ResolveEntity(IDispatchPtr(ei[0]), seg2geo, pts);
                if (n >= 2) b = ResolveEntity(IDispatchPtr(ei[1]), seg2geo, pts);
                ::SafeArrayUnaccessData(esa);
            }
        }

        // The primary ref must resolve; otherwise the relation binds the
        // origin / an external entity / unmapped geometry -> skip (same
        // policy as the FreeCAD reader).
        if (a.geo_id == 0xFFFFFFFFu) continue;

        // Dimensional magnitude (SI: metres / radians).
        double value = 0.0;
        if (value_bearing) {
            IDispatchPtr ddisp = rel->GetDisplayDimension();
            if (ddisp) {
                IDisplayDimensionPtr dd(ddisp);
                if (dd) {
                    IDimensionPtr dim = dd->IGetDimension();
                    if (dim) value = dim->GetSystemValue();
                }
            }
            if (ct != cadapp::SkConsType::Angle) value *= scale;  // angles stay radians
        }

        // RADIUS / DIAMETER on an arc -> the Arc* variant.
        if (ct == cadapp::SkConsType::CircleRadius || ct == cadapp::SkConsType::CircleDiameter) {
            for (const auto& g : out.geos) {
                if (g.id == a.geo_id) {
                    if (g.type == cadapp::SkGeoType::Arc) {
                        ct = (ct == cadapp::SkConsType::CircleRadius)
                                 ? cadapp::SkConsType::ArcRadius
                                 : cadapp::SkConsType::ArcDiameter;
                    }
                    break;
                }
            }
        }

        cadapp::SkConsIR c;
        c.id      = next_cons_id++;
        c.type    = ct;
        c.a       = a;
        c.b       = b;
        c.value   = value;
        c.driving = true;
        out.cons.push_back(c);
    }
    ::SafeArrayUnaccessData(sa);
}

// Map a sketch-local (x, y) -- already unit-scaled -- to world coordinates
// using the sketch plane (origin / x_dir / normal; y_dir = normal x x_dir).
// Used to lift a revolve's sketch-centerline axis into the world frame the
// Replayer revolves in.
void SketchLocalToWorld(const cadapp::SketchIR& sk, double lx, double ly,
                        double w[3])
{
    const double* o = sk.plane_origin;
    const double* x = sk.plane_x_dir;
    const double* n = sk.plane_normal;
    double y[3] = {                       // y_dir = normal x x_dir
        n[1] * x[2] - n[2] * x[1],
        n[2] * x[0] - n[0] * x[2],
        n[0] * x[1] - n[1] * x[0],
    };
    for (int i = 0; i < 3; ++i) {
        w[i] = o[i] + lx * x[i] + ly * y[i];
    }
}

// Read XYZ (first 3 doubles) of an ICurve::Evaluate(t) result into p.
bool EvalCurvePoint(ICurvePtr c, double t, double p[3])
{
    _variant_t ev = c->Evaluate(t);
    if (ev.vt != (VT_ARRAY | VT_R8)) {
        return false;
    }
    SAFEARRAY* sa = ev.parray;
    long lb = 0, ub = -1;
    ::SafeArrayGetLBound(sa, 1, &lb);
    ::SafeArrayGetUBound(sa, 1, &ub);
    double* d = nullptr;
    bool ok = false;
    if (SUCCEEDED(::SafeArrayAccessData(sa, (void**)&d))) {
        if (ub - lb + 1 >= 3) { p[0] = d[0]; p[1] = d[1]; p[2] = d[2]; ok = true; }
        ::SafeArrayUnaccessData(sa);
    }
    return ok;
}

// Describe a B-rep edge as a TopoRefIR for the Replayer's geometric resolver:
// curve MIDPOINT (point) + unit tangent there (normal) + arc length (measure)
// + the manifold 2-face adjacency (adj_count). Tangent is a central finite
// difference, so the only layout assumption is that Evaluate's first three
// doubles are the point.
bool EdgeToRef(IEdgePtr e, double scale, cadapp::TopoRefIR& ref)
{
    if (!e) {
        return false;
    }
    ICurvePtr c = e->IGetCurve();
    if (!c) {
        return false;
    }

    // Edge parameter range: GetCurveParams2 -> [sx,sy,sz, ex,ey,ez, t0, t1].
    double t0 = 0.0, t1 = 1.0;
    {
        _variant_t cp = e->GetCurveParams2();
        if (cp.vt == (VT_ARRAY | VT_R8)) {
            SAFEARRAY* sa = cp.parray;
            long lb = 0, ub = -1;
            ::SafeArrayGetLBound(sa, 1, &lb);
            ::SafeArrayGetUBound(sa, 1, &ub);
            double* d = nullptr;
            if (SUCCEEDED(::SafeArrayAccessData(sa, (void**)&d))) {
                if (ub - lb + 1 >= 8) { t0 = d[6]; t1 = d[7]; }
                ::SafeArrayUnaccessData(sa);
            }
        }
    }

    double tmid = 0.5 * (t0 + t1);
    double pm[3];
    if (!EvalCurvePoint(c, tmid, pm)) {
        return false;
    }

    double eps = (t1 - t0) * 1e-4;
    if (eps <= 0.0) eps = 1e-6;
    double pa[3], pb[3], tang[3] = { 0.0, 0.0, 0.0 };
    if (EvalCurvePoint(c, tmid - eps, pa) && EvalCurvePoint(c, tmid + eps, pb)) {
        double dx = pb[0] - pa[0], dy = pb[1] - pa[1], dz = pb[2] - pa[2];
        double len = std::sqrt(dx * dx + dy * dy + dz * dz);
        if (len > 1e-12) { tang[0] = dx / len; tang[1] = dy / len; tang[2] = dz / len; }
    }

    ref.kind      = cadapp::TopoRefIR::Kind::Edge;
    ref.point[0]  = pm[0] * scale; ref.point[1] = pm[1] * scale; ref.point[2] = pm[2] * scale;
    ref.normal[0] = tang[0]; ref.normal[1] = tang[1]; ref.normal[2] = tang[2];
    ref.adj_count = 2;                       // a fillet edge is manifold (2 faces)
    double L = 0.0;
    try { L = c->GetLength3(t0, t1); } catch (...) {}
    ref.measure   = L * scale;               // arc length
    return true;
}

} // namespace


// ---- SwReader ----------------------------------------------------------

SwReader::SwReader()  = default;
SwReader::~SwReader() = default;

bool SwReader::ReadFile(const std::string& path,
                        cadapp::DocumentIR& out,
                        std::string*       err_msg)
{
    auto fail = [&](const std::string& m) -> bool {
        if (err_msg) *err_msg = m;
        return false;
    };

    m_name_to_id.clear();
    m_next_feature_id     = 1;
    m_next_sketch_geo_id  = 1;
    m_next_sketch_cons_id = 1;
    out.source   = "sw";
    out.doc_path = path;

    bool ok = false;
    std::string err;

    // SolidWorks automation is an out-of-process STA COM server. Calling
    // it synchronously on the editor's UI thread pumps the Win32 message
    // loop, which re-enters the script VM through input callbacks
    // (keyreleased, ...) mid-load and crashes ("does not implement").
    // Run the whole COM session on a dedicated worker thread instead: the
    // UI thread blocks on join(), which does NOT pump messages, so no
    // editor events are dispatched during the load.
    std::thread worker([&]() {
    // COM apartment. If the host already initialized this thread with a
    // different model we must not tear it down on the way out.
    HRESULT hrco = ::CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);
    bool we_init = SUCCEEDED(hrco);
    try
    {
        // Connect: reuse a running SolidWorks if present, else launch one.
        CLSID clsid;
        if (FAILED(::CLSIDFromProgID(L"SldWorks.Application", &clsid))) {
            throw std::runtime_error("SolidWorks COM class not registered");
        }
        ISldWorksPtr swApp;
        {
            IUnknownPtr unk;
            if (::GetActiveObject(clsid, nullptr, &unk) == S_OK && unk) {
                swApp = unk;
            }
        }
        if (!swApp) {
            if (FAILED(swApp.CreateInstance(clsid)) || !swApp) {
                throw std::runtime_error("failed to launch SolidWorks");
            }
        }
        // Headless: best effort, ignore failures.
        try { swApp->Visible = VARIANT_FALSE; } catch (...) {}

        // Document type from extension.
        long doc_type = 1; // swDocPART
        if (EndsWithICase(path, ".sldasm")) {
            doc_type = 2; // swDocASSEMBLY
        } else if (EndsWithICase(path, ".slddrw")) {
            doc_type = 3; // swDocDRAWING
        }

        long errors = 0, warnings = 0;
        _bstr_t bpath(Widen(path).c_str());
        IModelDoc2Ptr model = swApp->OpenDoc6(
            bpath, doc_type, /*swOpenDocOptions_Silent*/ 1, _bstr_t(L""),
            &errors, &warnings);
        if (!model) {
            throw std::runtime_error("OpenDoc6 failed (errors=" +
                                     std::to_string(errors) + ")");
        }
        std::string title = Utf8(model->GetTitle());

        // FeatureManager, for rolling the model back when reading a
        // feature's edge / face selections (see the Fillet branch).
        IFeatureManagerPtr fm = model->GetFeatureManager();
        bool did_rollback = false;

        // Body chain: first solid-producing feature gets Base={0}
        // (fresh body); later ones chain off the running tip.
        uint32_t body_tip_id = 0;
        bool     have_tip     = false;

        // Walk the FeatureManager design tree.
        for (IFeaturePtr feat = model->IFirstFeature();
             feat;
             feat = feat->IGetNextFeature())
        {
            std::string type_name = Utf8(feat->GetTypeName2());
            std::string disp_name  = Utf8(feat->GetName());

            if (type_name == "ProfileFeature")
            {
                // ---- sketch ----
                ISketchPtr sketch = feat->GetSpecificFeature2();
                if (!sketch) {
                    continue;
                }

                uint32_t fid = m_next_feature_id++;

                cadapp::SketchIR sk;
                sk.feature_id = fid;
                sk.name       = disp_name;
                ReadSketchPlane(sketch, m_unit_scale, sk);

                // Correlation tables for mapping relation entities back to
                // the geos emitted here (segment identity + endpoint coords).
                std::vector<std::pair<long, uint32_t>> seg2geo;
                std::vector<PtRef>                     pts;

                _variant_t v = sketch->GetSketchSegments();
                if (v.vt == (VT_ARRAY | VT_DISPATCH)) {
                    SAFEARRAY* sa = v.parray;
                    long lb = 0, ub = -1;
                    ::SafeArrayGetLBound(sa, 1, &lb);
                    ::SafeArrayGetUBound(sa, 1, &ub);
                    IDispatch** items = nullptr;
                    if (SUCCEEDED(::SafeArrayAccessData(sa, (void**)&items))) {
                        for (long i = lb; i <= ub; ++i) {
                            ISketchSegmentPtr seg(items[i - lb]);
                            if (seg) {
                                uint32_t gid = m_next_sketch_geo_id++;
                                AppendSegment(seg, gid, m_unit_scale, sk);
                                RecordSegmentRefs(seg, gid, m_unit_scale,
                                                  seg2geo, pts);
                            }
                        }
                        ::SafeArrayUnaccessData(sa);
                    }
                }

                // Relations + dimensions -> SkConsIR (needs the geos above).
                // Best-effort: a constraint-read hiccup must not abort the
                // whole load -- the sketch still loads with its geometry.
                try {
                    ReadSketchConstraints(sketch, m_unit_scale, seg2geo, pts,
                                          m_next_sketch_cons_id, sk);
                } catch (const _com_error&) {
                    // leave sk.cons as-is (possibly partial); geometry stands
                }

                out.sketches.push_back(std::move(sk));

                cadapp::FeatPayloadSketch pl;
                pl.sketch_id = fid;
                cadapp::FeatureIR f;
                f.id   = fid;
                f.type = cadapp::FeatType::Sketch;
                f.name = disp_name;
                f.data = std::move(pl);
                out.features.push_back(std::move(f));
                m_name_to_id[disp_name] = fid;
            }
            else if (type_name == "Extrusion" || type_name == "Boss" ||
                     type_name == "Cut"       || type_name == "ICE")
            {
                // ---- boss / cut extrude ----
                // SolidWorks reports extrudes under several GetTypeName2
                // tokens: "Extrusion"/"Boss" are additive, "Cut"/"ICE" (a
                // legacy "intelligent cut extrude" name) are subtractive.
                const bool boss_ext = (type_name == "Extrusion" ||
                                       type_name == "Boss");
                IExtrudeFeatureData2Ptr ed = feat->GetDefinition();
                if (!ed) {
                    continue;
                }

                uint32_t fid = m_next_feature_id++;

                cadapp::FeatPayloadExtrude pl;

                // Profile sketch: the extrude's first ProfileFeature
                // sub-feature. Match its (localized) name to the sketch
                // id we emitted earlier.
                for (IFeaturePtr sub = feat->IGetFirstSubFeature();
                     sub;
                     sub = sub->IGetNextSubFeature())
                {
                    if (Utf8(sub->GetTypeName2()) == "ProfileFeature") {
                        auto it = m_name_to_id.find(Utf8(sub->GetName()));
                        if (it != m_name_to_id.end()) {
                            pl.sketch_id = it->second;
                        }
                        break;
                    }
                }

                // Direction defaults to the sketch normal; the Replayer
                // resolves world-space direction from the sketch plane.
                pl.direction[0] = 0.0; pl.direction[1] = 0.0; pl.direction[2] = 1.0;

                pl.distance       = ed->GetDepth(VARIANT_TRUE)  * m_unit_scale;
                pl.end_type       = MapEndCond(ed->GetEndCondition(VARIANT_TRUE));
                pl.flip_direction = (ed->ReverseDirection == VARIANT_TRUE);

                if (ed->BothDirections == VARIANT_TRUE) {
                    pl.distance2 = ed->GetDepth(VARIANT_FALSE) * m_unit_scale;
                    pl.end_type2 = MapEndCond(ed->GetEndCondition(VARIANT_FALSE));
                }

                cadapp::FeatureIR f;
                f.id   = fid;
                f.name = disp_name;
                f.type = boss_ext
                           ? cadapp::FeatType::BossExtrude
                           : cadapp::FeatType::CutExtrude;

                // Body chain Base input.
                if (!have_tip) {
                    f.input_feature_ids.push_back(0u);
                    f.input_roles.push_back(cadapp::InputRole::Base);
                } else {
                    f.input_feature_ids.push_back(body_tip_id);
                    f.input_roles.push_back(cadapp::InputRole::Base);
                }
                f.data = std::move(pl);

                m_name_to_id[disp_name] = fid;
                out.features.push_back(std::move(f));
                body_tip_id = fid;
                have_tip    = true;
            }
            else if (type_name == "Revolution" || type_name == "RevCut")
            {
                // ---- boss / cut revolve ---- ("Revolution" additive,
                // "RevCut" subtractive)
                IRevolveFeatureData2Ptr rd = feat->GetDefinition();
                if (!rd) {
                    continue;
                }
                // The axis entity and the boss/cut flag are SELECTION-based:
                // the feature-data interface only returns them validly while
                // selections are accessed. (Extrude needs none -- it reads no
                // selection.) Release at the end of the branch.
                VARIANT_BOOL rd_acc = rd->AccessSelections(model, nullptr);

                uint32_t fid = m_next_feature_id++;

                cadapp::FeatPayloadRevolve pl;

                // Profile sketch: first ProfileFeature sub-feature (same as
                // extrude). The revolve axis usually lives in this sketch.
                for (IFeaturePtr sub = feat->IGetFirstSubFeature();
                     sub;
                     sub = sub->IGetNextSubFeature())
                {
                    if (Utf8(sub->GetTypeName2()) == "ProfileFeature") {
                        auto it = m_name_to_id.find(Utf8(sub->GetName()));
                        if (it != m_name_to_id.end()) {
                            pl.sketch_id = it->second;
                        }
                        break;
                    }
                }

                pl.angle          = rd->GetRevolutionAngle(VARIANT_TRUE);  // radians
                pl.flip_direction = (rd->GetReverseDirection() == VARIANT_TRUE);

                // Axis: the revolve's axis entity is typically a sketch
                // centerline (ISketchLine) in the profile sketch. Lift its
                // endpoints into world via that sketch's plane. Anything else
                // (ref axis / edge) leaves the default world-Z axis + a note.
                const cadapp::SketchIR* psk = nullptr;
                for (const auto& s : out.sketches) {
                    if (s.feature_id == pl.sketch_id) { psk = &s; break; }
                }
                ISketchLinePtr axisLine = TryQI<ISketchLinePtr>(rd->GetAxis());
                if (axisLine && psk) {
                    ISketchPointPtr a = axisLine->IGetStartPoint2();
                    ISketchPointPtr b = axisLine->IGetEndPoint2();
                    if (a && b) {
                        double wa[3], wb[3];
                        SketchLocalToWorld(*psk, a->GetX() * m_unit_scale,
                                           a->GetY() * m_unit_scale, wa);
                        SketchLocalToWorld(*psk, b->GetX() * m_unit_scale,
                                           b->GetY() * m_unit_scale, wb);
                        double d[3] = { wb[0]-wa[0], wb[1]-wa[1], wb[2]-wa[2] };
                        double len = std::sqrt(d[0]*d[0] + d[1]*d[1] + d[2]*d[2]);
                        if (len > 1e-12) {
                            for (int i = 0; i < 3; ++i) {
                                pl.axis_origin[i] = wa[i];
                                pl.axis_dir[i]    = d[i] / len;
                            }
                        }
                    }
                }
                // else: axis stays the default world-Z through the origin
                // (a ref-axis / edge revolve we don't lift yet).

                // Discriminate boss/cut on the feature type name (IsBossFeature()
                // proved unreliable -- it returned false for a base boss revolve).
                cadapp::FeatureIR f;
                f.id   = fid;
                f.name = disp_name;
                f.type = (type_name == "Revolution")
                           ? cadapp::FeatType::BossRevolve
                           : cadapp::FeatType::CutRevolve;

                // Body chain Base input.
                if (!have_tip) {
                    f.input_feature_ids.push_back(0u);
                } else {
                    f.input_feature_ids.push_back(body_tip_id);
                }
                f.input_roles.push_back(cadapp::InputRole::Base);
                f.data = std::move(pl);

                m_name_to_id[disp_name] = fid;
                out.features.push_back(std::move(f));
                body_tip_id = fid;
                have_tip    = true;

                if (rd_acc == VARIANT_TRUE) {
                    rd->ReleaseSelectionAccess();
                }
            }
            else if (type_name == "Fillet")
            {
                // ---- constant-radius fillet (edge references) ----
                // Roll the model back to BEFORE this fillet first: its edge
                // selections reference geometry on the pre-fillet body (often
                // edges created by an earlier fillet), which AccessSelections
                // only resolves when the model is at that state -- without the
                // rollback later fillets read back zero edges.
                if (fm && fm->EditRollback(
                        /*swMoveRollbackBarToBeforeFeature*/ 3,
                        _bstr_t(Widen(disp_name).c_str())) == VARIANT_TRUE) {
                    did_rollback = true;
                }

                // Variable-radius fillets give IVariableFilletFeatureData2;
                // TryQI yields null for those and we skip. Edges are
                // selection-based -> AccessSelections.
                ISimpleFilletFeatureData2Ptr fd =
                    TryQI<ISimpleFilletFeatureData2Ptr>(feat->GetDefinition());
                if (!fd) {
                    continue;
                }
                VARIANT_BOOL fd_acc = fd->AccessSelections(model, nullptr);

                uint32_t fid = m_next_feature_id++;

                cadapp::FeatPayloadFillet pl;
                pl.radius = fd->GetDefaultRadius() * m_unit_scale;

                _variant_t ev = fd->GetEdges();
                if (ev.vt == (VT_ARRAY | VT_DISPATCH)) {
                    SAFEARRAY* sa = ev.parray;
                    long lb = 0, ub = -1;
                    ::SafeArrayGetLBound(sa, 1, &lb);
                    ::SafeArrayGetUBound(sa, 1, &ub);
                    IDispatch** items = nullptr;
                    if (SUCCEEDED(::SafeArrayAccessData(sa, (void**)&items))) {
                        for (long i = lb; i <= ub; ++i) {
                            IEdgePtr e = TryQI<IEdgePtr>(items[i - lb]);
                            cadapp::TopoRefIR ref;
                            if (EdgeToRef(e, m_unit_scale, ref)) {
                                pl.edges.push_back(ref);
                            }
                        }
                        ::SafeArrayUnaccessData(sa);
                    }
                }

                // Face picks: a constant-radius ("Simple") fillet can select a
                // whole FACE, meaning "round every edge of this face". SW stores
                // those in face-list 1 with nothing in GetEdges. Expand each
                // picked face into its boundary edges so the edge-based fillet
                // payload + replay cover them without a new IR concept.
                _variant_t fv = fd->GetFaces(1);
                if (fv.vt == (VT_ARRAY | VT_DISPATCH)) {
                    SAFEARRAY* sa = fv.parray;
                    long lb = 0, ub = -1;
                    ::SafeArrayGetLBound(sa, 1, &lb);
                    ::SafeArrayGetUBound(sa, 1, &ub);
                    IDispatch** items = nullptr;
                    if (SUCCEEDED(::SafeArrayAccessData(sa, (void**)&items))) {
                        for (long i = lb; i <= ub; ++i) {
                            IFace2Ptr face = TryQI<IFace2Ptr>(items[i - lb]);
                            if (!face) continue;
                            _variant_t ev2 = face->GetEdges();
                            if (ev2.vt != (VT_ARRAY | VT_DISPATCH)) continue;
                            SAFEARRAY* sa2 = ev2.parray;
                            long l2 = 0, u2 = -1;
                            ::SafeArrayGetLBound(sa2, 1, &l2);
                            ::SafeArrayGetUBound(sa2, 1, &u2);
                            IDispatch** e2 = nullptr;
                            if (SUCCEEDED(::SafeArrayAccessData(sa2, (void**)&e2))) {
                                for (long j = l2; j <= u2; ++j) {
                                    IEdgePtr e = TryQI<IEdgePtr>(e2[j - l2]);
                                    cadapp::TopoRefIR ref;
                                    if (EdgeToRef(e, m_unit_scale, ref)) {
                                        pl.edges.push_back(ref);
                                    }
                                }
                                ::SafeArrayUnaccessData(sa2);
                            }
                        }
                        ::SafeArrayUnaccessData(sa);
                    }
                }

                cadapp::FeatureIR f;
                f.id   = fid;
                f.name = disp_name;
                f.type = cadapp::FeatType::Fillet;

                if (!have_tip) {
                    f.input_feature_ids.push_back(0u);
                } else {
                    f.input_feature_ids.push_back(body_tip_id);
                }
                f.input_roles.push_back(cadapp::InputRole::Base);
                f.data = std::move(pl);

                m_name_to_id[disp_name] = fid;
                out.features.push_back(std::move(f));
                body_tip_id = fid;
                have_tip    = true;

                if (fd_acc == VARIANT_TRUE) {
                    fd->ReleaseSelectionAccess();
                }
            }
            else
            {
                // Unrecognised feature. Skip the non-solid system entries
                // (datum planes, origin, folders, lights, sensors, coord
                // systems, materials); everything else is a real modelling
                // feature we don't type YET -- emit it as opaque so the gap
                // is VISIBLE in the IR (coverage grows as these turn into
                // typed payloads) instead of silently vanishing.
                static const char* const kSkip[] = {
                    "RefPlane", "OriginProfileFeature", "CoordSys", "RefAxis",
                    "DetailCabinet", "MateGroup", "DimXpertManager",
                    "LightsCamerasAndScene", "Material", "SketchBlockDef",
                    "Attribute",
                };
                bool skip = type_name.find("Folder") != std::string::npos
                         || type_name.find("Light")  != std::string::npos
                         || type_name.find("Sensor") != std::string::npos;
                for (const char* s : kSkip) {
                    if (type_name == s) { skip = true; break; }
                }

                if (!skip)
                {
                    if (m_strict) {
                        throw std::runtime_error("unhandled feature type: " + type_name);
                    }
                    // Opaque: visible in the IR, no shape, NOT wired into the
                    // body chain (so the recognised features still replay).
                    uint32_t fid = m_next_feature_id++;
                    cadapp::FeatPayloadOpaque pl;
                    pl.strings["sw_type"] = type_name;
                    cadapp::FeatureIR f;
                    f.id   = fid;
                    f.name = disp_name;
                    f.type = cadapp::FeatType::Unknown;
                    f.data = std::move(pl);
                    f.ext_strings["sw_type"] = type_name;
                    out.features.push_back(std::move(f));
                    m_name_to_id[disp_name] = fid;
                }
            }
        }

        // Restore the rollback bar to the end so the document is left in its
        // full-model state (and CloseDoc doesn't persist a rolled-back view).
        if (fm && did_rollback) {
            fm->EditRollback(/*swMoveRollbackBarToEnd*/ 1, _bstr_t(L""));
        }

        // Close the document but leave SolidWorks running for reuse.
        swApp->CloseDoc(_bstr_t(Widen(title).c_str()));
        ok = true;
    }
    catch (const _com_error& e)
    {
        err = "SolidWorks COM error: " + Utf8(e.Description()) + " (hr=0x" +
              [](HRESULT h){ char b[16]; std::snprintf(b, sizeof b, "%08lx", (unsigned long)h); return std::string(b); }(e.Error()) + ")";
    }
    catch (const std::exception& e)
    {
        err = e.what();
    }
    catch (...)
    {
        err = "unknown SolidWorks reader error";
    }

    if (we_init) {
        ::CoUninitialize();
    }
    }); // worker
    worker.join();

    if (!ok) {
        return fail(err.empty() ? "SwReader failed" : err);
    }
    return true;
}

} // namespace cadcvt

#else // !CAX_SW_OK

namespace cadcvt
{
SwReader::SwReader()  = default;
SwReader::~SwReader() = default;

bool SwReader::ReadFile(const std::string&, cadapp::DocumentIR&, std::string* err_msg)
{
    if (err_msg) {
        *err_msg = "SwReader not built (SolidWorks type libraries not found at "
                   "configure time; set CAX_SW_TLB_DIR)";
    }
    return false;
}
} // namespace cadcvt

#endif // CAX_SW_OK
